<?php
namespace App\Http\Controllers;
use App\Models\User;use App\Models\Store;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Facades\Http;use Illuminate\Support\Str;use Laravel\Socialite\Facades\Socialite;
class OAuthController extends Controller{
 public function google(){return Socialite::driver('google')->scopes(['openid','profile','email'])->redirect();}
 public function googleCallback(){try{$p=Socialite::driver('google')->user();}catch(\Throwable $e){return redirect()->route('login')->withErrors(['email'=>'Google sign-in could not be completed.']);}return $this->loginOrCreate('google',(string)$p->getId(),$p->getEmail(),$p->getName()?:'KuStore user',$p->getAvatar());}
 public function kuartalRedirect(Request $r){$cfg=config('services.kuartal_id');abort_unless($cfg['client_id']&&$cfg['client_secret'],503,'Kuartal ID sign-in is not configured.');$discovery=Http::timeout(8)->get($cfg['issuer'].'/.well-known/openid-configuration')->throw()->json();$state=Str::random(64);$nonce=Str::random(64);$verifier=Str::random(96);$challenge=rtrim(strtr(base64_encode(hash('sha256',$verifier,true)),'+/','-_'),'=');$r->session()->put('kustore_oidc',['state'=>$state,'nonce'=>$nonce,'verifier'=>$verifier]);$q=http_build_query(['client_id'=>$cfg['client_id'],'redirect_uri'=>$cfg['redirect'],'response_type'=>'code','scope'=>'openid profile email','state'=>$state,'nonce'=>$nonce,'code_challenge'=>$challenge,'code_challenge_method'=>'S256']);return redirect()->away($discovery['authorization_endpoint'].'?'.$q);}
 public function kuartalCallback(Request $r){$s=$r->session()->pull('kustore_oidc');if(!$s||!hash_equals($s['state']??'',(string)$r->query('state')))return redirect()->route('login')->withErrors(['email'=>'Kuartal ID sign-in session expired or was invalid.']);if($r->query('error'))return redirect()->route('login')->withErrors(['email'=>'Kuartal ID sign-in was cancelled.']);$cfg=config('services.kuartal_id');$discovery=Http::timeout(8)->get($cfg['issuer'].'/.well-known/openid-configuration')->throw()->json();$token=Http::asForm()->timeout(10)->post($discovery['token_endpoint'],['grant_type'=>'authorization_code','client_id'=>$cfg['client_id'],'client_secret'=>$cfg['client_secret'],'redirect_uri'=>$cfg['redirect'],'code'=>$r->query('code'),'code_verifier'=>$s['verifier']])->throw()->json();$info=Http::withToken($token['access_token'])->timeout(10)->get($discovery['userinfo_endpoint'])->throw()->json();if(($info['iss']??$cfg['issuer'])!==$cfg['issuer']||empty($info['sub'])||empty($info['email']))abort(403,'Invalid Kuartal ID identity.');return $this->loginOrCreate('kuartal_id',(string)$info['sub'],$info['email'],$info['name']??'Kuartal user',null);}
 private function loginOrCreate(string $provider,string $providerId,string $email,string $name,?string $avatar){$user=User::where($provider.'_id',$providerId)->orWhere('email',$email)->first();if(!$user){$user=User::create(['name'=>$name,'email'=>$email,'password'=>null,$provider.'_id'=>$providerId]);}else{$user->forceFill([$provider.'_id'=>$providerId,'name'=>$user->name?:$name])->save();}if(!$user->store()->exists()){$base=Str::slug(Str::before($email,'@'))?:Str::slug($name)?:'store';$username=$base;$n=1;while(Store::where('username',$username)->exists())$username=$base.'-'.$n++;Store::create(['user_id'=>$user->id,'username'=>$username,'display_name'=>$name,'avatar_url'=>$avatar,'published'=>true]);}Auth::login($user,true);return redirect()->intended(route('dashboard.index'));}
}